package dkarelin.ru.rxjavaexample_1.storio;


import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType;



@StorIOSQLiteType(table = "users")
public class User {

    /**
     * If object was not inserted into db, id will be null
     */
    @Nullable
    @StorIOSQLiteColumn(name = "_id", key = true)
    Long id;

    // For example: "artem_zin", without "@".
    @NonNull
    @StorIOSQLiteColumn(name = "name")
    String name;


    @NonNull
    @StorIOSQLiteColumn(name = "age")
    String age;


    @NonNull
    @StorIOSQLiteColumn(name = "info")
    String info;


    // leave default constructor for AutoGenerated code!
    User() {

    }





    @NonNull
    public static User newUser(@Nullable Long id, @NonNull String name, @NonNull String age, @NonNull String info) {
        User user = new User();
        user.id = id;
        user.name = name;
        user.age = age;
        user.info = info;
        return user;
    }

    @Nullable
    public Long id() {
        return id;
    }

    @NonNull
    public String age() {
        return age;
    }

    @NonNull
    public String info() {
        return info;
    }

    @NonNull
    public String name() {
        return name;
    }






    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        User user = (User) o;

        if (id != null ? !id.equals(user.id) : user.id != null) return false;
        return name.equals(user.name);
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + name.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", nick='" + name + '\'' +
                '}';
    }
}
